/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragracingproject;

import javax.swing.JInternalFrame;

/**
 *
 * @author bbsuser
 */
public class DragRaceForm extends javax.swing.JFrame {

    /**
     * Creates new form DragRaceForm
     */
    public DragRaceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFrame = new javax.swing.JFrame();
        tfPlayer1 = new javax.swing.JTextField();
        tfPlayer2 = new javax.swing.JTextField();
        btnContenue = new javax.swing.JButton();
        pbFuelPlayer1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pbFuelPlayer2 = new javax.swing.JProgressBar();
        lblPlayer2Name = new javax.swing.JLabel();
        lblPlayer1Name = new javax.swing.JLabel();
        btnBreakePlayer2 = new javax.swing.JButton();
        btnContinuePlayer2 = new javax.swing.JButton();
        btnAccelerationPlayer2 = new javax.swing.JButton();
        btnAccelerationplayer1 = new javax.swing.JButton();
        btncontinuplayer1 = new javax.swing.JButton();
        btnBreakeplayer1 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();

        loginFrame.setMinimumSize(new java.awt.Dimension(323, 194));

        btnContenue.setText("Continue");
        btnContenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginFrameLayout = new javax.swing.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContenue)
                .addGap(121, 121, 121))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFrameLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnContenue)
                .addGap(47, 47, 47))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(648, 624));

        pbFuelPlayer1.setMaximum(25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fuel");
        jLabel1.setName("lblFuelPlayer1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Fuel");
        jLabel2.setName("lblFuelPlayer2"); // NOI18N

        pbFuelPlayer2.setMaximum(25);
        pbFuelPlayer2.setToolTipText("");
        pbFuelPlayer2.setName("pbPlayer2"); // NOI18N

        lblPlayer2Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlayer2Name.setText("Spieler2");

        lblPlayer1Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlayer1Name.setText("Spieler1");

        btnBreakePlayer2.setText("Bremsen");
        btnBreakePlayer2.setName("btnBrake"); // NOI18N
        btnBreakePlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBreakePlayer2ActionPerformed(evt);
            }
        });

        btnContinuePlayer2.setText("Weiterfahren");
        btnContinuePlayer2.setName("btnContinue"); // NOI18N
        btnContinuePlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuePlayer2ActionPerformed(evt);
            }
        });

        btnAccelerationPlayer2.setText("Beschleunigen");
        btnAccelerationPlayer2.setName("btnAcceleration"); // NOI18N
        btnAccelerationPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccelerationPlayer2ActionPerformed(evt);
            }
        });

        btnAccelerationplayer1.setText("Beschleunigen");
        btnAccelerationplayer1.setName("btnAccelerationplayer1"); // NOI18N
        btnAccelerationplayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccelerationplayer1ActionPerformed(evt);
            }
        });

        btncontinuplayer1.setText("Weiterfahren");
        btncontinuplayer1.setName("btnContinue"); // NOI18N
        btncontinuplayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontinuplayer1ActionPerformed(evt);
            }
        });

        btnBreakeplayer1.setText("Bremsen");
        btnBreakeplayer1.setName("btnBrake"); // NOI18N
        btnBreakeplayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBreakeplayer1ActionPerformed(evt);
            }
        });

        canvas1.setBackground(new java.awt.Color(51, 102, 255));
        canvas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        canvas2.setBackground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAccelerationplayer1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBreakeplayer1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btncontinuplayer1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(pbFuelPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblPlayer1Name)
                        .addGap(96, 96, 96)
                        .addComponent(lblPlayer2Name))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnContinuePlayer2)
                                    .addComponent(btnBreakePlayer2)
                                    .addComponent(btnAccelerationPlayer2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(pbFuelPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer1Name)
                    .addComponent(lblPlayer2Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pbFuelPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pbFuelPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAccelerationplayer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncontinuplayer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBreakeplayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAccelerationPlayer2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnContinuePlayer2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBreakePlayer2)
                                .addGap(23, 23, 23))))
                    .addComponent(canvas2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(canvas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccelerationPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccelerationPlayer2ActionPerformed
        // TODO add your handling code here:
        pbFuelPlayer2.setValue(pbFuelPlayer2.getValue()-2);
        auto1.speed = auto1.speed +1;
                if(pbFuelPlayer2.getValue() <= 0)
        {
            Lostmethod(tfPlayer2.getText());
        }
    }//GEN-LAST:event_btnAccelerationPlayer2ActionPerformed

    private void btnAccelerationplayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccelerationplayer1ActionPerformed
        // TODO add your handling code here:
        pbFuelPlayer1.setValue(pbFuelPlayer1.getValue()-2);
        auto2.speed = auto2.speed +1;
                if(pbFuelPlayer1.getValue() <= 0)
        {
            Lostmethod(tfPlayer1.getText());
        }
    }//GEN-LAST:event_btnAccelerationplayer1ActionPerformed

    private void btncontinuplayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontinuplayer1ActionPerformed
        // TODO add your handling code here:
        pbFuelPlayer1.setValue(pbFuelPlayer1.getValue()-1);
                if(pbFuelPlayer1.getValue() <= 0)
        {
            Lostmethod(tfPlayer1.getText());
        }
    }//GEN-LAST:event_btncontinuplayer1ActionPerformed

    private void btnBreakeplayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBreakeplayer1ActionPerformed
        // TODO add your handling code here:
        auto1.speed = auto1.speed-1;
    }//GEN-LAST:event_btnBreakeplayer1ActionPerformed

    private void btnContinuePlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuePlayer2ActionPerformed
        // TODO add your handling code here:
        pbFuelPlayer2.setValue(pbFuelPlayer2.getValue()-1);
        if(pbFuelPlayer2.getValue() <= 0)
        {
            Lostmethod(tfPlayer2.getText());
        }
            
    }//GEN-LAST:event_btnContinuePlayer2ActionPerformed

    private void btnBreakePlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBreakePlayer2ActionPerformed
        // TODO add your handling code here:
        auto2.speed = auto2.speed-1;
    }//GEN-LAST:event_btnBreakePlayer2ActionPerformed

    private void btnContenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContenueActionPerformed
        // TODO add your handling code here:
        spieler1 = new Spieler(tfPlayer1.getText());
        spieler2 = new Spieler(tfPlayer2.getText());
        dform.setVisible(true);
        dform.loginFrame.setVisible(false);
        startmethod();
    }//GEN-LAST:event_btnContenueActionPerformed

    private void startmethod()
    {
      pbFuelPlayer1.setValue(25);
      pbFuelPlayer2.setValue(25);
      lblPlayer1Name.setText(tfPlayer1.getText());
      lblPlayer2Name.setText(tfPlayer2.getText());
      spieler1.setcar(auto1);
      spieler2.setcar(auto2);
      auto1.speed = 0;
      auto2.speed = 0;     
    }
    
    private void Lostmethod(String name)
    {
     System.out.println( name + " Lost");
        dform.setVisible(false);
        dform.loginFrame.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    private Spieler spieler1;
    private Spieler spieler2;
    private Auto auto1 = new Auto();
    private Auto auto2 = new Auto();
    private static DragRaceForm dform;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DragRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DragRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DragRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DragRaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dform = new DragRaceForm();
                dform.setVisible(false);               
                dform.loginFrame.setVisible(true);
            }           
        });       
    }

  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccelerationPlayer2;
    private javax.swing.JButton btnAccelerationplayer1;
    private javax.swing.JButton btnBreakePlayer2;
    private javax.swing.JButton btnBreakeplayer1;
    private javax.swing.JButton btnContenue;
    private javax.swing.JButton btnContinuePlayer2;
    private javax.swing.JButton btncontinuplayer1;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPlayer1Name;
    private javax.swing.JLabel lblPlayer2Name;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JProgressBar pbFuelPlayer1;
    private javax.swing.JProgressBar pbFuelPlayer2;
    private javax.swing.JTextField tfPlayer1;
    private javax.swing.JTextField tfPlayer2;
    // End of variables declaration//GEN-END:variables
}
